finalize kutchi/Kutchi-ITI/kutchiProject/kutchiProject/urls.py
from django.contrib import admin
from django.conf import settings
from django.urls import path, include
from django.conf.urls.static import static

urlpatterns = [path("admin/", admin.site.urls), path("", include("myapp.urls"))]


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

finalize kutchi/Kutchi-ITI/kutchiProject/myapp/urls.py
from django.urls import path
from myapp import views

urlpatterns = [
    path("login/", views.loginPage, name="login"),
    path("logout/", views.logoutPage, name="logout"),
    path("", views.index, name="home"),
    path(
        "studentregister/<int:user_id>/",
        views.studentRegisterForm,
        name="student-register",
    ),
    path("studentsignup/", views.studentSignup, name="studentsignup"),
    path("studentdetails/<int:pk>/", views.studentDetails, name="studentdetails"),
    path("deletestudent/<int:pk>/", views.deleteStudent, name="delete"),
    path("editstudent/<int:pk>/", views.editStudent, name="edit"),
    path("addcourse/", views.addCourse, name="addcourse"),
    path("coursedetails/<int:pk>/", views.courseDetails, name="coursedetails"),
    path("deletecourse/<int:pk>/", views.courseDelete, name="delete-course"),
    path("updatecourse/<int:pk>/", views.courseUpdate, name="update-course"),
    path("student-tab/", views.studentTab, name="student-tab"),
    path("course-tab/", views.courseTab, name="course-tab"),
    path("contact-tab/", views.contactTab, name="contact"),
    path("about-tab/", views.aboutTab, name="about"),
    path("enquiry-tab/", views.enquiryTab, name="enquiry"),
    path("fees-tab/", views.feesTab, name="feestab"),
    path("servicesform/", views.services_form, name="servicesform"),
    path("rulesregulation/", views.rules_and_regulations, name="rulesregulation"),
    path("faculties/", views.faculties, name="faculties"),
    path("examreport/<int:pk>", views.examReport, name="examreport"),
    path("updateexamreport/<int:pk>/", views.editExamReport, name="updateexamreport"),
    path("sidebar/", views.sidebarmenu, name="sidebar"),
    path(
        "loggedin-students-details/",
        views.loggedin_student_details,
        name="loggedin-students-details",
    ),
    path(
        "studentlist_inside_studenttab/",
        views.studentlist_inside_studenttab,
        name="studentlist_inside_studenttab",
    ),
    path(
        "courselist_inside_coursetab/",
        views.courselist_inside_coursetab,
        name="courselist_inside_coursetab",
    ),
    path(
        "enquiries_inside_enquirytab/",
        views.enquiries_inside_enquirytab,
        name="enquiries_inside_enquirytab",
    ),
    path("syllabus/<int:pk>/", views.DownloadSyllabus, name="syllabusdownload"),
    path("download-pdf/<int:pk>/", views.download_pdf, name="download-pdf"),
    path("remarks/<int:pk>/", views.StudentRemark, name="remarks"),
    path("addenquiry", views.addenquiry, name="addenquiry"),
    path("payment_history/<int:pk>/", views.payment_history, name="payment_history"),
    path("add_installment/<int:pk>/", views.add_installment, name="add_installment"),
    path("cancel_admission/<int:pk>/", views.cancel_admission, name="cancel_admission"),
    path("search/", views.search_students, name="search_students"),
    path("searchcourse/", views.search_courses, name="search_courses"),
    path("print_exam_reports/", views.print_exam_reports, name="print_exam_reports"),
]

finalize kutchi/Kutchi-ITI/kutchiProject/myapp/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone
from django.db.models.signals import pre_save
from django.dispatch import receiver
from datetime import timedelta
from dateutil.relativedelta import relativedelta
from datetime import date

# Create your models here.


class Courses(models.Model):
    coursename = models.CharField(max_length=100)
    coursedetails = models.TextField(null=True, blank=True)
    courseduration = models.PositiveIntegerField(default=0)
    coursefees = models.IntegerField()
    file_path = models.CharField(max_length=200, null=True, blank=True)
    # updated = models.DateTimeField(auto_now=True)
    # created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.coursename


class Batch(models.Model):
    batch_day = models.CharField(max_length=100, null=True, blank=True)
    batch_time = models.CharField(max_length=100, default="8:30 pm - 10:30 pm")

    def __str__(self):
        return f"{self.batch_day} - {self.batch_time}"


class studentsModel(models.Model):
    user = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    firstname = models.CharField(max_length=50)
    lastname = models.CharField(max_length=50)
    rollno = models.IntegerField(default=0)
    age = models.IntegerField()
    gender = models.CharField(max_length=20)
    occupation = models.CharField(max_length=200, default="Student")
    phoneno = models.BigIntegerField()
    emailid = models.EmailField()
    address = models.TextField(null=True, blank=True)
    coursename = models.ForeignKey(Courses, on_delete=models.SET_NULL, null=True)
    joiningdate = models.DateField()
    joiningtime = models.TimeField(auto_now_add=True)
    completiondate = models.DateField()
    extendeddate = models.DateField(null=True, blank=True)
    exam_date = models.DateField(null=True, blank=True)
    exam_given = models.BooleanField(default=False)
    coursefees = models.IntegerField()
    batch_day = models.ForeignKey(
        Batch,
        on_delete=models.SET_NULL,
        null=True,
        related_name="students_with_batch_day",
        blank=True,
    )
    batch_time = models.ForeignKey(
        Batch,
        on_delete=models.SET_NULL,
        null=True,
        related_name="students_with_batch_time",
    )
    initial_payment = models.IntegerField(default=0)
    feespaid = models.IntegerField(default=0)
    admissioncancel = models.BooleanField(default=False)
    updated = models.DateTimeField(auto_now=True)
    created = models.DateTimeField(auto_now_add=True)

    def save(self, *args, **kwargs):
        if self.coursename:
            # Autofill coursefees from related Courses
            self.coursefees = self.coursename.coursefees

        if not self.feespaid:
            self.feespaid = self.initial_payment

        if self.joiningdate and self.coursename and self.coursename.courseduration:
            # Calculate completion date by adding course duration (in months)
            self.completiondate = self.joiningdate + relativedelta(
                months=self.coursename.courseduration
            )

        # Always set exam date as 1 day after completion date
        if self.completiondate:
            self.exam_date = self.completiondate + timedelta(days=1)

        if self.exam_date and self.exam_date <= date.today():
            self.exam_given = True
        else:
            self.exam_given = False

        super().save(*args, **kwargs)

    def is_admission_canceled(self):
        return self.admissioncancel

    def __str__(self):
        return self.firstname


class StudentRemarks(models.Model):
    student = models.ForeignKey(studentsModel, on_delete=models.SET_NULL, null=True)
    remark_date = models.DateField()
    remarks = models.CharField(max_length=500)

    def save(self, *args, **kwargs):
        # Automatically set the remark_date to the current date if not provided
        if not self.remark_date:
            self.remark_date = date.today()
        super().save(*args, **kwargs)

    def __str__(self):
        return f"Remark for {self.student.firstname} on {self.remark_date}"


class contact(models.Model):
    name = models.CharField(max_length=100)
    useremail = models.EmailField()
    message = models.TextField()


class SyllabusDownloadRecord(models.Model):
    name = models.CharField(max_length=100)
    email = models.EmailField()
    number = models.CharField(max_length=20)
    download_time = models.DateTimeField(auto_now_add=True)


class Enquiry(models.Model):
    firstname = models.CharField(max_length=50)
    lastname = models.CharField(max_length=50)
    phoneno = models.BigIntegerField()
    address = models.TextField(null=True, blank=True)
    reference = models.CharField(max_length=50)

    def __str__(self):
        return self.firstname + self.lastname


class FeesInstallment(models.Model):
    student = models.ForeignKey(studentsModel, on_delete=models.CASCADE)
    date = models.DateField()
    time = models.TimeField()
    amount_paid = models.DecimalField(max_digits=10, decimal_places=2)


class ExamReports(models.Model):
    student = models.ForeignKey(studentsModel, on_delete=models.CASCADE)
    coursename = models.ForeignKey(Courses, on_delete=models.SET_NULL, null=True)
    exam_status = models.BooleanField(default=False)  # Use BooleanField for checkbox
    theory_marks = models.DecimalField(max_digits=5, decimal_places=2)
    practical_marks = models.DecimalField(max_digits=5, decimal_places=2)
    total_marks = models.DecimalField(max_digits=5, decimal_places=2)
    percentage = models.DecimalField(max_digits=5, decimal_places=2)
    marksheet_no = models.IntegerField()
    hallticket_no = models.IntegerField(default=0)


class Services(models.Model):
    student = models.ForeignKey(
        studentsModel, on_delete=models.SET_NULL, null=True, default=None
    )

    student_name = models.CharField(max_length=100)
    rollno = models.IntegerField()
    coursename = models.CharField(max_length=100)
    phoneno = models.BigIntegerField()
    request_date = models.DateField(auto_now_add=True)
    is_completed = models.BooleanField(default=False)
    # Servives
    change_batch_time = models.BooleanField(default=False)
    extend_batch_time = models.BooleanField(default=False)
    special_batch = models.BooleanField(default=False)
    course_rejoin = models.BooleanField(default=False)
    course_extend = models.BooleanField(default=False)
    course_duration_extend = models.BooleanField(default=False)
    course_break = models.BooleanField(default=False)
    fast_track = models.BooleanField(default=False)
    extra_practice = models.BooleanField(default=False)
    name_correction = models.BooleanField(default=False)
    installment_extend = models.BooleanField(default=False)
    trust_letter = models.BooleanField(default=False)
    duplicate_id = models.BooleanField(default=False)
    duplicate_certificate = models.BooleanField(default=False)
    certificate_marksheet_bypost = models.BooleanField(default=False)
    reissue_book = models.BooleanField(default=False)
    reissue_hall_ticket = models.BooleanField(default=False)
    re_exam = models.BooleanField(default=False)
    recheck_exampaper = models.BooleanField(default=False)
    attendance_chart = models.BooleanField(default=False)
    mobile_num_change = models.BooleanField(default=False)
    holiday_leave = models.BooleanField(default=False)
    change_faculty = models.BooleanField(default=False)
    fine_or_penalty_waivedoff = models.BooleanField(default=False)
    cancel_admission = models.BooleanField(default=False)
    other_services = models.BooleanField(default=False)
    # request details
    request_details = models.TextField(null=True, blank=True, default=None)
    # agreement
    policy_agreement = models.BooleanField(default=False)

    def __str__(self):
        return f"Service Request for {self.student}"

finalize kutchi/Kutchi-ITI/kutchiProject/myapp/forms.py
from django.forms import ModelForm, DateInput
from .models import (
    studentsModel,
    Courses,
    SyllabusDownloadRecord,
    StudentRemarks,
    Enquiry,
    FeesInstallment,
    ExamReports,
    Services,
    contact,
)
from django import forms


class StudentModelForm(ModelForm):
    class Meta:
        model = studentsModel
        fields = "__all__"
        exclude = [
            "completiondate",
            "coursefees",
            "exam_date",
            "exam_given",
            "feespaid",
        ]
        widgets = {
            "joiningdate": DateInput(attrs={"type": "date"}),
            "completiondate": DateInput(attrs={"type": "date"}),
        }

    coursename = forms.ModelChoiceField(queryset=Courses.objects.all())


class CourseModelForm(ModelForm):
    file_path = forms.FilePathField(path="pdfs/", required=False)

    class Meta:
        model = Courses
        fields = "__all__"


class SyllabusDownloadForm(forms.ModelForm):
    class Meta:
        model = SyllabusDownloadRecord
        fields = ["name", "email", "number"]


class RemarksForm(ModelForm):
    class Meta:
        model = StudentRemarks
        fields = ["remarks"]


class EnquiryForm(ModelForm):
    class Meta:
        model = Enquiry
        fields = "__all__"


class FeesInstallmentForm(forms.ModelForm):
    class Meta:
        model = FeesInstallment
        fields = ["date", "time", "amount_paid"]
        widgets = {
            "date": DateInput(attrs={"type": "date"}),
            "time": forms.TimeInput(attrs={"type": "time"}),
        }


class ExamReportsForm(forms.ModelForm):
    class Meta:
        model = ExamReports
        fields = "__all__"
        exclude = ["student", "coursename"]

    exam_status = forms.BooleanField(
        required=False,  # Checkbox field is not required
        widget=forms.CheckboxInput(attrs={"class": "form-check-input"}),
    )


class ServiceForm(ModelForm):
    # def __init__(self, *args, **kwargs):
    #     super(ServiceForm, self).__init__(*args, **kwargs)

    #     # Disable the "Student" dropdown field
    #     self.fields['student'].widget.attrs['disabled'] = 'disabled'
    class Meta:
        model = Services
        fields = "__all__"


class contactForm(ModelForm):
    class Meta:
        model = contact
        fields = "__all__"

finalize kutchi/Kutchi-ITI/kutchiProject/myapp/templates/myapp/HomeCarousal.html
<style>

    .heading-container {
        margin-top: 180px;
        text-align: center;
      }
    
      .sub-heading {
        font-size: 80px;
        color: rgba(125, 233, 255);
        transition: color 0.3s;
      }
    
      .sub-heading:hover {
        color: #fa0505;
      }
    
      .main-heading {
        position: relative;
        font-size: 36px;
        font-weight: bold;
        color: black;
        margin-top: -15px;
        transition: color 0.3s;
      }
    
      .main-heading::before,
      .main-heading::after {
        content: "";
        position: absolute;
        width: 50px;
        height: 3px;
        background-color: #007bff;
        top: 50%;
        transform: translateY(-50%);
        transition: background-color 0.3s;
      }
    
      .main-heading::before {
        left: 280px;
      }
    
      .main-heading::after {
        right: 280px; /* Adjusted value to make it closer */
      }
    
      .main-heading:hover {
        color: #007bff;
      }
    
      .main-heading:hover::before,
      .main-heading:hover::after {
        background-color: #555;
      }
    
    
  .w-100 {
    width: 100%!important;
    height: 823px;
}

.carousel-caption {
    position: absolute;
    right: 15%;
    bottom: 1.25rem;
    left: 15%;
    padding-top: 1.25rem;
    padding-bottom: 1.25rem;
    color: #fff;
    text-align: center;
    margin-bottom: 300px;
}

.main-heading2{
  position: relative;
  font-size: 36px;
  font-weight: bold;
  color: black;
  margin-top: -15px;
  transition: color 0.3s;
}
.main-heading2::before {
  left: 280px;
}

.main-heading2::after {
  right: 280px; /* Adjusted value to make it closer */
}

.main-heading2:hover {
  color: #007bff;
}

.main-heading2:hover::before,
.main-heading2:hover::after {
  background-color: #555;
}

</style>


<div class="mainbody">
    <div id="carouselExampleCaptions" class="carousel slide" data-bs-ride="carousel">
        <div class="carousel-indicators">
          <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="0" class="active" aria-current="true" aria-label="Slide 1"></button>
          <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="1" aria-label="Slide 2"></button>
          <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="2" aria-label="Slide 3"></button>
        </div>
        <div class="carousel-inner">
          <div class="carousel-item active">
            <img src="static/images/background.png" class="d-block w-100" alt="...">
            <div class="carousel-caption d-none d-md-block">
                <div class="sub-heading">
                    Kutchi
                </div>
                <div class="main-heading">
                    Indian Technical Institute
                  </div>
            </div>
          </div>
          <div class="carousel-item">
            <img src="static/images/background2.png" class="d-block w-100" alt="...">
            <div class="carousel-caption d-none d-md-block">
                <div class="sub-heading">
                    Kutchi
                </div>
                <div class="main-heading2">
                    Indian Technical Institute
                  </div>
            </div>
          </div>
          <div class="carousel-item">
            <img src="static/images/background.png" class="d-block w-100" alt="...">
            <div class="carousel-caption d-none d-md-block">
                <div class="sub-heading">
                    Kutchi
                </div>
                <div class="main-heading">
                    Indian Technical Institute
                  </div>
            </div>
          </div>
        </div>
        <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide="prev">
          <span class="carousel-control-prev-icon" aria-hidden="true"></span>
          <span class="visually-hidden">Previous</span>
        </button>
        <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide="next">
          <span class="carousel-control-next-icon" aria-hidden="true"></span>
          <span class="visually-hidden">Next</span>
        </button>
      </div>
    <div>

finalize kutchi/Kutchi-ITI/kutchiProject/myapp/templates/myapp/enquiries_inside_enquirytab.html
<style>
    body {
        font-family: Arial, sans-serif;
        background-color: #f4f4f4;
    }

    .table-container{
        margin-top:50px
    }

    .container1 {
        position: relative;
        width: 80%;
        margin: auto;
        padding: 20px;
        background-color: white;
        box-shadow: 0px 0px 10px rgba(0, 0, 0, 0.1);
        border-radius: 10px;
        transition: box-shadow 0.3s;
    }
    .container1:hover{
        box-shadow: 0 12px 16px 0 rgba(0,0,0,0.24), 
        0 25px 60px 0 rgba(0,0,0,0.19);
    }

    table {
        width: 100%;
        border-collapse: collapse;
        margin-top: 20px;
    }

    th, td {
        padding: 12px;
        text-align: left;
        border-bottom: 1px solid #ddd;
    }

    th {
        background-color: #f9f9f9;
    }

    tr:hover {
        background-color: #d9d4d4;
    }

    h2 {
        margin-top: 0;
        color: #1e3d56;
    }

    .custom-button {
        position: absolute;
        top: 0;
        right: 0;
        margin: 10px;
        
        display: inline-block;
        padding: 15px 30px;
        background-color: #1e3d56;
        color: white;
        font-size: 18px;
        border: none;
        border-radius: 5px;
        cursor: pointer;
        transition: background-color 0.3s, transform 0.2s;
    }

    .custom-button:hover {
        background-color: #0056b3;
        transform: scale(1.05);
    }

</style>

<div class="table-container">
<div class="container1">
    <button class="custom-button" onclick="location.href='{% url 'addenquiry' %}'">New Enquiry</button>
    <h2>All Enquiries</h2>
    <table>
        <tr>
            <th>Name</th>
            <th>Phone Number</th>
            <th>Address</th>
            <th>Reference</th>
        </tr>

        {% for enquiry in enquirylist %}
        <tr {% for student in students %}
            {% if enquiry.firstname == student.firstname and enquiry.phoneno == student.phoneno %}
                style="background-color: lightgreen;" {# You can set your desired background color here #}
            {% endif %}
        {% endfor %}>
            <td>{{ enquiry.firstname }} {{ enquiry.lastname }}</td>
            <td>{{ enquiry.phoneno }}</td>
            <td>{{ enquiry.address }}</td>
            <td>{{ enquiry.reference }}</td>
        </tr>
    {% endfor %}
    
    </table>
</div>
</div>

finalize kutchi/Kutchi-ITI/kutchiProject/myapp/templates/myapp/enquiry_comp.html
{% extends 'base.html' %}

{% block title %}Enquiry{% endblock title %}

{% block content %}

<style>
    .studentPage{
        margin-left: 120px
    }



</style>

<div class="studentPage"> 
    {% include 'myapp/enquiries_inside_enquirytab.html' %}
    
</div> 

{% endblock content %}

finalize kutchi/Kutchi-ITI/kutchiProject/myapp/templates/myapp/loggedin_student_details.html
<!DOCTYPE html>
<html>
<head>
<style>
    body {
        font-family: Arial, sans-serif;
        background-color: #f4f4f4;
    }

    .container {
        width: 95%;
        margin: auto;
        margin-top: 0px;
        padding: 20px;
        background-color: white;
        box-shadow: 0px 0px 10px rgba(0, 0, 0, 0.1);
        border-radius: 10px;
    }

    .student-details {
        display: flex;
        flex-wrap: wrap;
        justify-content: space-between;
        margin-bottom: 20px;
    }

    .detail {
        color:white;
        width: 48%;
        padding: 10px;
        background-color: #b20237;
        border-radius: 5px;
        box-shadow: 0px 0px 5px rgba(0, 0, 0, 0.1);
    }

    .detail:hover{
        box-shadow: 0 12px 16px 0 rgba(0,0,0,0.24), 
        0 25px 60px 0 rgba(0,0,0,0.19);
        background-color: #1e3d56;
    }

    .remarks-detail{
        color:white;
        width: 48%;
        padding: 10px;
        background: linear-gradient(to bottom, #e02b0b, #e00b0b);
        border-radius: 5px;
        box-shadow: 0px 0px 5px rgba(0, 0, 0, 0.1);
    }
    .remarks-detail:hover{
        box-shadow: 0 12px 16px 0 rgba(0,0,0,0.24), 
        0 25px 60px 0 rgba(0,0,0,0.19);
    }

    .fees-detail{
        color:white;
        margin-left: 240px;
        width: 65%;
        padding: 10px;
        background-color: #1e3d56;
        border-radius: 35px;
        box-shadow: 0px 0px 5px rgba(0, 0, 0, 0.1);
    }
    .fees-detail:hover{
        box-shadow: 0 12px 16px 0 rgba(0,0,0,0.24), 
        0 25px 60px 0 rgba(0,0,0,0.19);
        background-color: #b20237;
    }

    h2 {
        margin-top: 0;
        color: #007bff;
    }

    p {
        margin: 5px 0;
    }

    .examreportbtn{
        display: inline-block;
        padding: 5px 20px;
        background-color: #bf512c;
        color: white;
        font-size: 18px;
        border: none;
        border-radius: 25px;
        margin-left:0px;
        cursor: pointer;
        transition: background-color 0.3s, transform 0.2s; 
    }
    .examreportbtn:hover{
        background-color: #e00b0f;
        transform: scale(1.05);
    }

    /* Media Query for screens 700px and below */
    @media (max-width: 700px) {
        .detail, .remarks-detail, .fees-detail {
            width: 100%;
            margin-left: 0;
            margin-bottom: 3vh;
        }
    }
    
</style>
</head>
<body>

<div class="container">
    {% if students.is_admission_canceled %}
        <h2 style="color:red"><b>YOUR ADMISSION HAS BEEN CANCELLED</b></h2>
    {% else %}
        <h2>Your Details</h2>
    {% endif %}
    
    <div class="student-details">
        <div class="detail">
            <h3>Personal Information</h3>
            <p><strong>Name:</strong> {{students.firstname}} {{ students.lastname }}</p>
            <p><strong>Seriel Number:</strong>  {{students.id}}</p>
            <p><strong>Roll Number:</strong> {{students.rollno}} </p>

            <p><strong>Age:</strong>  {{ students.age }}</p>
            <p><strong>Gender:</strong> {{ students.gender }}</p>
            <p><strong>Phone:</strong> {{ students.phoneno }}</p>
            <p><strong>Email:</strong> {{ students.emailid }}</p>
        </div>
        <div class="detail">
            <!-- &#8377; is a rupees symbol -->
            <h3>Course Information</h3>
            <p><strong>Course:</strong> {{ students.coursename }}</p>
            <p><strong>Joining Date:</strong> {{ students.joiningdate|date:"F d, Y" }}</p>
            <p><strong>Completion Date:</strong>  {{ students.completiondate|date:"F d, Y" }}</p>
            <p><strong>Total Course Duration:</strong> {{duration.years}} Years, {{ duration.months }} Months, {{ duration.days }} Days</p>
            <p><strong>Total Fees:</strong> &#8377;{{ students.coursefees }}</p>    
            <p><strong>Fees Paid:</strong> &#8377;{{ students.feespaid }}</p>
            <p><strong>Remaining Balance:</strong> &#8377;{{ remainingBalance }}</p>
            <p><strong>Batch and Timing:</strong> {{students.batch_time}}</p>
            {% if students.extendeddate %}
                <p style="background-color:red"><strong>Course Extention Date:</strong> {{students.extendeddate}}</p>
            {% else %}
                <p><strong>Course Extention Date:</strong> {{students.extendeddate}}</p>
            {% endif %}
            
        </div>
    </div>

    <div class="student-details">
        <div class="fees-detail">
            <h3>Fees Details</h3>
            <p><strong>Total Fees:</strong> &#8377;{{ students.coursefees }}</p>    
            <p><strong>Initial amount Paid:</strong> &#8377;{{ students.initial_payment }}</p>    
            <p><strong>Fees Paid:</strong> &#8377;{{ students.feespaid }}</p>
            <p><strong>Remaining Balance:</strong> &#8377;{{ remainingBalance }}</p>
        </div>
    </div>

    <div class="student-details">
        <div class="detail">
            <h3>Address</h3>
            <p>{{ students.address }}</p>
            <!-- <p>City, State</p>
            <p>Zip Code</p> -->
        </div>
        <div class="detail">
            <h3>Emergency Contact</h3>
            <p><strong>Name:</strong>  {{students.firstname}} {{ students.lastname }}</p>
            <p><strong>Occupation:</strong> Student</p>
            <p><strong>Phone:</strong> {{ students.phoneno }}</p>
        </div>
    </div>

    <div class="student-details">
        {% load custom_filters %}
        <div class="detail">
            <h3>Exam and Certification</h3>

            <div class="exam-status">
                {% if students.exam_given %}
                    <p><strong>Exam Status:</strong>  Given</p>
                {% else %}
                    <p><strong>Exam Status:</strong>  Exam Pending</p>
                {% endif %}
            </div>
            
            {% comment %} <p><strong>Exam Date:</strong> {{ students.completiondate|add_days:1|date:"F d, Y" }}</p> {% endcomment %}
            <p><strong>Exam Date:</strong> {{ students.exam_date|date:"F d, Y"  }}</p>
            <p><strong>Exam Fees:</strong>&#8377;100 </p>
            <p><strong>Exam Session:</strong> </p>
            <p><strong>Exam Attempt:</strong> </p>
            <p><strong>Re-Exam:</strong> </p>
            <p><strong>Certification:</strong>  {{ students.coursename }}</p>
            <p><strong>Certification no:</strong> </p>
            <p><strong>Result Date:</strong> </p>
        </div>

        <div class="remarks-detail">
            <!-- &#8377; is a rupees symbol -->
            <h3>Remarks</h3>
            <ul>
                {% for remark in students.studentremarks_set.all %}
                    <li>{{ remark.remark_date|date:"F d, Y" }}: {{ remark.remarks }}</li>
                {% endfor %}

                {% if request.user.is_superuser %}
                    <button class="addremarkbtn" onclick="location.href='{% url 'remarks' students.id %}'">Add a Remark</button>
                {% endif %}
            </ul>
        </div>
    </div>

    <div class="student-details">
        <div class="fees-detail">
            <h3>Examination Reports</h3>
            <button class="examreportbtn" onclick="location.href='{% url 'print_exam_reports' %}'">view exam report</button>
            
            {% comment %} {% if exam_reports %}
                <!-- Iterate through the exam_reports queryset -->
                {% for exam_report in exam_reports %}
                    <p><strong>Status:</strong>
                    {% if exam_report.exam_status %}
                        Given
                    {% else %}
                        Not Given
                    {% endif %}
                    </p>    
                    <p><strong>Theoretical Marks:</strong> {{ exam_report.theory_marks }} Marks</p>    
                    <p><strong>Practical Marks:</strong> {{ exam_report.practical_marks }} Marks</p>
                    <p><strong>Total Marks:</strong> {{ exam_report.total_marks }} Marks</p>
                    <p><strong>Percentage:</strong> {{ exam_report.percentage }}%</p>
                    <p><strong>Marksheet no:</strong> {{ exam_report.marksheet_no }}</p>
                    
                {% endfor %}
            {% else %}
                <p>No exam reports available.</p>
            {% endif %} {% endcomment %}
        </div>
    </div>
    
</div>

</body>
</html>